[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[colors.dim]
black = "#32302f"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#928374"
yellow = "#b57614"

[colors.normal]
#black = "#282828"
#blue = "#458588"
#cyan = "#689d6a"
#green = "#98971a"
#magenta = "#b16286"
#red = "#cc241d"
#white = "#a89984"
#yellow = "#d79921"
black = "#282828"
blue = "#7a8688"
cyan = "#8d9d8d"
green = "#989889"
magenta = "#b19fa7"
red = "#ccb8b8"
white = "#a89984"
yellow = "#d7cfc1"


[colors.primary]
background = "#181818"
bright_foreground = "#f9f5d7"
dim_foreground = "#f2e5bc"
foreground = "#fbf1c7"

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 13.0

[font.bold]
family = "DankMono Nerd Font"
style = "Bold"

[font.italic]
family = "DankMono Nerd Font"
style = "Italic"

[font.normal]
family = "DankMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10
