return {
    'nvim-treesitter/nvim-treesitter',
    opts = {
        ensure_isntalled = {
            "lua",
            "python",
            "go",
            "html",
            "htmldjango",
            "javascript",
            "typescript",
            "vue",
            "json",
            "yaml",
            "scss",
            "sql",
            "rust",
            "prisma",
            "markdown",
            "terraform",
            "toml",
            "git_config",
            "git_rebase",
            "gitcommit",
            "gitignore",
            "ssh_config",
            "nginx",
            "bash",
            "sway",
        },
        auto_install = true,
    },
}
